[project]
name = "hashmap"
version = "0.1.0"
description = "HashMap Implementation for UZH ESC 413"
readme = "README.md"
authors = [
    { name = "SilvanW", email = "silvan.wiedmer@bluewin.ch" }
]
requires-python = ">=3.13"
dependencies = [
    "sympy>=1.14.0",
]

[dependency-groups]
dev = [
    "pytest>=9.1.1",
]

[tool.pytest.ini_options]
testpaths = ["tests"]
pythonpath = ["src"]
